title: Panaché Vëlo Everesting
description: Saturday, 27th June 2026, Bourscheid, Luxembourg
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
